package constants

// This module contains environment variable names

const DNS_AUTH_TOKEN = "DNS_AUTH_TOKEN"
const DNS_AUTH_TOKEN_FILE = "DNS_AUTH_TOKEN_FILE"
const DNS_AUTH_TOKEN_VAULT = "DNS_AUTH_TOKEN_VAULT"
const DNS_AUTH_TOKEN_SECRET = "DNS_AUTH_TOKEN_SECRET"
const DNS_RESOLVERS = "DNS_RESOLVERS"
const DNS_TIMEOUT = "DNS_TIMEOUT"
const DISABLE_CP = "DISABLE_CP"
const DOMAINS = "DOMAINS"
const FILENAME = "FILENAME"
const ACCOUNT_EMAIL = "ACCOUNT_EMAIL"
const ACCOUNT_KEY_FILE = "ACCOUNT_KEY_FILE"
const LE_TOS_AGREED = "LE_TOS_AGREED"
const CA_DIR = "CA_DIR"
const LE_CRT_KEY_TYPE = "LE_CRT_KEY_TYPE"
const OUTPUT_DIRECTORY = "OUTPUT_DIRECTORY"
